### PR TITLE
checking diff on my fork first

### PR DESCRIPTION
**Pull request by petegilb**

### CODE REVIEW

**Review by Aherys — APPROVED** [review]
Go from DW.

**Review by Aherys — COMMENTED** [review]
I suggest to let the GetWorld in protected, and remove the one in private instead.

There is no reason for a getworld to be in private (if we are talking about the same change)

**Comment by petegilb** [comment]
> I suggest to let the GetWorld in protected, and remove the one in private instead.
> 
> There is no reason for a getworld to be in private (if we are talking about the same change)

it's public :)

**Comment by Aherys** [comment]
Perfect !

**Pull request closed without merging**
